### ISSUE TITLE
I should see a pill that shows how many stars a GitHub resource has with the specified styling

### ISSUE THREAD

**Issue by ibagha** [concourse/resource-types-website#101]
Parent Epic: #207
**Pill**
Height: 16px
Padding/margin around left/right of text: 8px
Border radius: 5
Fill: Linear Gradient
rgba(242, 242, 242, 0.56) @ 0%
#EBEBEB @ 100%

**Text**
Font Family: Iosevka
Font Style: Regular
Font Size: 10px
Line Height: 12px
Line Height: 100%
Align: Center
Vertical Align: Center
Fill: Solid
#000000

**Star (icon)**
Width: 10px
Height: 10px
Color: #F5D62F
*see comment for icon

A/C 
- [ ] Pills should match the specified styling
- [ ] Regardless of the width of the content (i.e. 3 starts vs 2300) the margins around the star and text should stay the same
- [ ] Regarless of the width of the content, the pill should still have the same padding away from the github icon

Link to Figma: https://www.figma.com/file/pmLRwbPKrwDAGn6XLDoUiA/Concourse-Resources?node-id=507%3A5

**Comment by ibagha** [comment]
<img width="10" alt="star-icon" src="https://user-images.githubusercontent.com/54036938/66004935-e285f780-e45e-11e9-9236-9f5c419a4ef0.png">

**Comment by jomsie** [comment]
REGARDING ⭐️ COUNT
if 
0->999 : Display normal number
1000 -> 9999 : Display k (with one decimal place, aka 1.0k or 9.9k)
10000 -> 999999 : Display k (no decimal place, aka 10k, 999k)

@ibagha

**Comment by jomsie** [comment]
so my previous comment is _slightly_ off,

if its 
0->999, display normal number
anything higher, display with at max 1 decimal place (1000 should be 1k, 1100 should be 1.1k) and also allow rounding (as 9999 should be 10k not 9.9k)

**Comment by jomsie** [comment]
i'm also wondering if it's better to just do the rounding of the stars number on the backend... it seems pretty easy with [something like this (slightly different)](https://yourbasic.org/golang/round-float-2-decimal-places/), rather than trying to figure out all the cases for rounding a float to 1 decimal (aka 1950 -> 2k vs 1949 -> 1.9k) in elm, since all I can find is an integer round function.

there is a [third party library](https://github.com/myrho/elm-round/) we can use for elm, but it might just be easier/better to do it on the backend instead of bringing in another dependency that is probably unnecessary.

**Comment by jomsie** [comment]
remaining work:
- [ ] convert the int stars into the string count with the K, M ... etc.
- [ ] fix the pipeline.
- [ ] fix the unit tests to figure out the token problem.
- [ ] revert the frontend to use string stars
