### ISSUE TITLE
The skeleton of the cards should match the listed specs

### ISSUE THREAD

**Issue by ibagha** [concourse/resource-types-website#84]
Width: 280px
Height: 160px
Border Radius: 4
background: #FFFFFF;
Drop shadow: 0px 0px 2px rgba(0, 0, 0, 0.2), 0px 2px 3px rgba(0, 0, 0, 0.2);
Padding: 8px
Link to Figma: https://www.figma.com/file/pmLRwbPKrwDAGn6XLDoUiA/Concourse-Resources?node-id=508%3A0

**Comment by ibagha** [comment]
Height:
Width:
Border Radius:
Drop shadow:
Padding:
Link to Figma:

**Comment by YoussB** [comment]
- talk to @ibagha about the grid system.

**Comment by YoussB** [comment]
- 3 cards per row

**Comment by jomsie** [comment]
i'm going to also make this story _slightly_ bigger (creepin!) by implementing the grid and the resource list page to display multiple cards

**Comment by jomsie** [comment]
![Screen Shot 2019-11-27 at 11 17 29 AM](https://user-images.githubusercontent.com/2362482/69740541-8e6a5d00-1107-11ea-806e-a2c83d2bdccf.png)

^^ @ibagha @YoussB the skeleton card 

![Screen Shot 2019-11-27 at 11 18 28 AM](https://user-images.githubusercontent.com/2362482/69740610-a7730e00-1107-11ea-8660-574104cd163a.png)

^^ showing off the grid

**Comment by jomsie** [comment]
i'm going to timebox the responsiveness of the cards for _just_ this morning, because i've gotta look deeper into css grid.

**Comment by jomsie** [comment]
so after switching to elm-ui, i found some small issues. (they kinda span both this issue and #98)

1. elm-ui only supports a single box-shadow border style (https://github.com/mdgriffith/elm-ui/issues/51, https://github.com/mdgriffith/elm-ui/issues/98, etc). our mockups have 2 box-shadows by default, and 3 when hovering.

there is a fork of elm-ui which supports a list of shadows (https://github.com/rlefevre/elm-ui/commit/5e61e706409dda3309ff1dbcec3918571ecb23cf), but no PR that i can see.

i've tried to make the shadows look as close as possible using a single shadow elm-ui attribute, but if worse comes to worst, external stylesheet. because my next point...

2. elm-ui hover ([mouseover](https://package.elm-lang.org/packages/mdgriffith/elm-ui/1.1.5/Element#mouseOver)) doesn't support elm-ui compatibility [htmlAttribute](https://package.elm-lang.org/packages/mdgriffith/elm-ui/1.1.5/Element#htmlAttribute). (https://www.reddit.com/r/elm/comments/9ys9te/elmui_how_to_use_htmlattributesstyle_in_mouseover/) so i can't even use a custom `htmlAttribute` attribute with the three box shadows on hover because elm-ui's mouseover only allows decorations to change, while htmlAttribute is an attribute.

3. moving away from complaining about shadows, dealing with the grid we want hasn't been easily done (so far) with responsiveness and consistent centering. right now i've switched to a couple `htmlAttribute` to deal with grids, gaps, and columns. i'll probably spend a friday trying to get this working on elm-ui, but for now, i don't want to spend anymore workin' time on it.

**Comment by jomsie** [comment]
current structure for each component (banner, resource list, card, etc)

`Banner/Banner.elm` -> Set up some view types (ie. banner has a container, title, and body, container has height (integer), backgroundColor (RGB), backgroundImage(String)) and also retrieve styles for those types
`Banner/Styles.elm` -> Specify style values (ie. `bannerHeight` is 176)
`Banner/View.elm` -> Use elm-ui to bring it all together (ie. `column [height <| px container.height][]`)

@pivotal-jamie-klassen @YoussB any thoughts?

**Comment by jomsie** [comment]
Got some feedback to allow 4 cards max, and have a min margin on either side of around 70px.
